baseURL = "https://frankliu.org/dlbook-ig"
# relativeURLs = true
# uglyURLs = true
languageCode = "en-us"
title = "Reading of Deep Learning book"
theme = "ananke"
pygmentsCodeFences = true
# pygmentsUseClasses = true
# pygmentsUseClassic = false
canonifyURLs = true
SectionPagesMenu = "main"

